/*
 * Actions
 */

export const LOG_IN_REQUEST = "LOG_IN_REQUEST";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_ERROR = "LOG_IN_ERROR";
export const LOG_IN_CHECK = "LOG_IN_CHECK";

export const SAVE_URL_TO_REDIRECT_AFTER_LOGIN =
  "SAVE_URL_TO_REDIRECT_AFTER_LOGIN";
export const CLEAR_URL_TO_REDIRECT_AFTER_LOGIN =
  "CLEAR_URL_TO_REDIRECT_AFTER_LOGIN";
