/*
 * Actions
 */

export const LOG_IN_REQUEST = "LOG_IN_REQUEST";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_ERROR = "LOG_IN_ERROR";
export const LOG_IN_CHECK = "LOG_IN_CHECK";

export const SAVE_URL_TO_REDIRECT_AFTER_LOGIN =
  "SAVE_URL_TO_REDIRECT_AFTER_LOGIN";
export const CLEAR_URL_TO_REDIRECT_AFTER_LOGIN =
  "CLEAR_URL_TO_REDIRECT_AFTER_LOGIN";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FINISH_SUCCESS = "SIGN_UP_FINISH_SUCCESS";
export const SIGN_UP_FINISH_ERROR = "SIGN_UP_FINISH_ERROR";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";
export const SIGN_UP_DONE = "SIGN_UP_DONE";

export const TOKEN_REFRESH_REQUEST = "TOKEN_REFRESH_REQUEST";
export const TOKEN_REFRESH_SUCCESS = "TOKEN_REFRESH_SUCCESS";
export const TOKEN_EXPIRATION_TIMEOUT = "TOKEN_EXPIRATION_TIMEOUT";
