# Build deps stage
FROM node:14.19.1-alpine3.14 AS builder

RUN apk add --update --no-cache curl jq

WORKDIR /opt/app
COPY package.json package-lock.json ./

RUN npm ci

FROM node:14.19.1-alpine3.14 AS assets_builder

WORKDIR /opt/app

RUN apk add --update --no-cache jq

COPY --from=builder /opt/app/node_modules ./node_modules
COPY package.json package-lock.json ./
COPY public/ ./public
COPY src/ ./src

RUN npm run build