export const GET_GLOBAL_ARTICLE_REQUEST = "GET_GLOBAL_ARTICLE_REQUEST";
export const GET_GLOBAL_ARTICLE_SUCCESS = "GET_GLOBAL_ARTICLE_SUCCESS";
export const GET_GLOBAL_ARTICLE_ERROR = "GET_GLOBAL_ARTICLE_ERROR";

export const SET_PAGE_REQUEST = "SET_PAGE_REQUEST";
export const SET_PAGE_SUCCESS = "SET_PAGE_SUCCESS";
export const SET_PAGE_ERROR = "SET_PAGE_ERROR";

export const FIND_ARTICLE_REQUEST = "FIND_ARTICLE_REQUEST";
export const FIND_ARTICLE_SUCCESS = "FIND_ARTICLE_SUCCESS";
export const FIND_ARTICLE_ERROR = "FIND_ARTICLE_ERROR";

export const GET_COMMENTS_LIST_REQUEST = "GET_COMMENTS_LIST_REQUEST";
export const GET_COMMENTS_LIST_SUCCESS = "GET_COMMENTS_LIST_SUCCESS";
export const GET_COMMENTS_LIST_ERROR = "GET_COMMENTS_LIST_ERROR";

export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_ERROR = "POST_COMMENT_ERROR";
