export const GET_GLOBAL_ARTICLE_REQUEST = "GET_GLOBAL_ARTICLE_REQUEST";
export const GET_GLOBAL_ARTICLE_SUCCESS = "GET_GLOBAL_ARTICLE_SUCCESS";
export const GET_GLOBAL_ARTICLE_ERROR = "GET_GLOBAL_ARTICLE_ERROR";

export const SET_PAGE_REQUEST = "SET_PAGE_REQUEST";
export const SET_PAGE_SUCCESS = "SET_PAGE_SUCCESS";
export const SET_PAGE_ERROR = "SET_PAGE_ERROR";
